# Организация программ и методы строк
my_string = input('Здравствуйте, я выполняю 4-е задание: ')
print(my_string)
print(len(my_string))
print(my_string)
print(my_string .upper())
print(my_string .lower())
print(my_string .replace('Здравствуйте' , ' Привет'))
print(my_string[0])
print(my_string[-1])